version: '3.4'

volumes:
  tempory-file-storage:
  permanent-file-storage:

services:

  message.broker: 
    image: rabbitmq:3-management

  sql.db:
    image: mcr.microsoft.com/mssql/server:2017-latest

  ireckonu.fileuploadhost:
    image: ${DOCKER_REGISTRY-}ireckonufileuploadhost
    build:
      context: .
      dockerfile: src/Ireckonu.FileUploadHost/Dockerfile
    environment:
      - Storage__Temporary=storage/temporary
    volumes:
      - tempory-file-storage:/app/storage/temporary:rw
    depends_on:
      - sql.db
      - message.broker

  ireckonu.fileprocessinghost:
    image: ${DOCKER_REGISTRY-}ireckonufileprocessinghost
    build:
      context: .
      dockerfile: src/Ireckonu.FileProcessingHost/Dockerfile
    environment:
      - Storage__Temporary=storage/temporary
      - Storage__Permanent=storage/permanent
    volumes:
      - tempory-file-storage:/app/storage/temporary:rw
      - permanent-file-storage:/app/storage/permanent:rw
    depends_on:
      - sql.db
      - message.broker